load_data:
  duration_delete_value: 100
  save_location: 'data/raw'

clean:
  input_file_name: 'ks-projects-201801.csv'
  save_location: 'data/clean'
  output_file_name: 'train_cleaned.csv'

save_location: 'data/raw'

db_config:
  SQLALCHEMY_DATABASE_URI: 'sqlite:///database/msia423.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  SQLALCHEMY_ECHO: False  # If true, SQL for queries made will be printed

delete_columns:
- 'ID'
- 'usd_pledged_real'
- 'usd pledged'
- 'launched'
- 'deadline'
- 'name'
- 'backers'
- 'pledged'
      
train_model:  
  start: 
    seed: 42
    split: 0.1  
    params: 
      n_estimators: 150
      max_depth: 3
      learning_rate: 0.2
      min_samples_leaf: 1
      random_state: 3
  save_location: 'models' 
  model: 'GradientBoosting'
  version: 'v1'  


  path: ./eval
  file_name: 'evaluation.txt'
  f_name: 'GradientBoosting.pkl'

